# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Artificial Intelligence
author: Pantelis Monogioudis, Ph.D
copyright: "2023"  # Copyright year to be placed in the footer
logo: logo.png

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
  # exclude_patterns: 
  #   - data_mining/aiml-common/lectures/transfer-learning/quantized_transfer_learning.ipynb
    
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: ai-course.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - ai.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/pantelis/artificial-intelligence # artificial-intelligence  # Online location of your book
  path_to_book: artificial_intelligence/aiml_common #artificial_intelligence/aiml-common  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: true
  use_edit_page_button: false
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  baseurl: https://pantelis.github.io/artificial-intelligence

launch_buttons:
  colab_url: "https://colab.research.google.com"

sphinx:
  recursive_update: false
  config:
    html_theme_options:
      use_download_button: true
      repository_url: https://github.com/pantelis/artificial-intelligence
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: false
    mathjax3_config:
      tex:
        macros:
          #"N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
    latex_elements:
        preamble: |
          \newcommand\N{\mathbb{N}}
          \newcommand\floor[1]{\lfloor#1\rfloor}
          \newcommand{\bmat}{\left[\begin{array}}
          \newcommand{\emat}{\end{array}\right]}
  extra_extensions:
    - sphinxcontrib.youtube
    - sphinx_inline_tabs
    - sphinxcontrib.inkscapeconverter
    #- sphinx_click.ext
    - sphinx_inline_tabs
    - sphinxext.rediraffe
    - sphinx_proof
    - sphinxcontrib.mermaid
    - sphinxcontrib.seqdiag
    #- sphinx_examples

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - deflist
    - colon_fence
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution